/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const logo = function (name, url = '') {
  return (`<div class="sidebar-logo-item">
    ` + (
      (url != '') ?
      `<img src="${url}" width="32" height="32" alt="logo" />` : ``
    ) + `
    <text>${name}</text>
    </div>`);
};

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Just for reference
  oldSidebar: [{type: 'autogenerated', dirName: 'old'}],
  // Actually-used sidebars
  contributionSidebar: [
    {
      type: 'html',
      value: logo("Contribution"),
      defaultStyle: false,
    },
    {
      type: 'autogenerated',
      dirName: 'contribution',
    }
  ],
  omniariumStd1Sidebar: [
    {
      type: 'html',
      value: logo("Omniarium", "https://omni.ender.ing/brand/icons/logo.svg"),
      defaultStyle: false,
    },
    {
      type: 'autogenerated',
      dirName: 'omni-std1',
    }
  ],
};

export default sidebars;
